version: '3.8'

services:
  database:
    container_name: database
    platform: linux/amd64
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    platform: linux/amd64
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./back:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    platform: linux/amd64
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./back:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  app:
    container_name: app-dev
    platform: linux/amd64
    build:
      context: ./ui
      target: development
    volumes:
      - ./ui/src:/app/src
    ports:
      - 3000:3000