version: '3.8'

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  php:
    container_name: php
    platform: linux/amd64
    user: "1000:1000"
    environment:
      - APP_ENV=dev
      - COMPOSER_MEMORY_LIMIT=-1
      - DATABASE_URL=mysql://symfony:symfony@database:3306/symfony
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./back:/var/www/symfony_docker
      - composer_cache:/composer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
  nginx:
    container_name: nginx
    platform: linux/amd64
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./back:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  app:
    container_name: app-dev
    platform: linux/amd64
    build:
      context: ./ui
      target: development
    volumes:
      - ./ui:/var/www/app
      - /var/www/app/node_modules
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
  
volumes:
  db_data:
  composer_cache: